name: Docker Image CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  docker_build:
    runs-on: ubuntu-latest
    outputs:
      BUILD_TAG: ${{ steps.date.outputs.BUILD_TAG }}
    steps:
      - name: Get current date
        id: date
        run: echo "BUILD_TAG=$(date +%s)" >> $GITHUB_OUTPUT
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            pvsfair/home-library:${{ steps.date.outputs.BUILD_TAG }}
            pvsfair/home-library:latest
  deploy:
    runs-on: ubuntu-latest
    needs:
      - docker_build
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: pvsfair/argocd
          token: ${{secrets.GITOPS_TOKEN }}

      - name: setup kustomize
        uses: imranismail/setup-kustomize@v2

      - name: Set image tag
        run: kustomize edit set image pvsfair/home-library:${{needs.docker_build.outputs.BUILD_TAG}}
        working-directory: home-library

      - name: Commit changes
        run: |
          git config user.email "gitops@pvsfair.com"
          git config user.name "gitops"
          git add .
          git commit -am "Set 'home-library' image tag to '${{needs.docker_build.outputs.BUILD_TAG}}'"
          git pull --rebase
          git push
