name: Docker Image CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  docker_build:
    runs-on: ubuntu-latest
    steps:
      - name: Get current date
        id: date
        run: echo "BUILD_TAG=$(date +%s)" >> $GITHUB_OUTPUT
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            pvsfair/home-library:${{ steps.date.outputs.BUILD_TAG }}
            pvsfair/home-library:latest
